sudo: false
dist: trusty

compiler:
- g++

before_install:
   - wget https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_4_x/ViennaRNA-2.4.11.tar.gz
   - tar -zxvf ViennaRNA-2.4.11.tar.gz
   - cd ViennaRNA-2.4.11
   - ./configure
   - make
   - sudo make install


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gengetopt

before_script:
- autoreconf -i


script:
- ./configure
- make -j${CPU_COUNT}


before_deploy:
- make dist-gzip
- make dist-zip
- export DIST_GZIP=$(ls pourRNA-*.tar.gz)
- export DIST_ZIP=$(ls pourRNA-*.zip)
- echo "Deploying Changelog and autoconf's dists (${DIST_GZIP} and ${DIST_ZIP}) to GitHub releases"


deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  overwrite: true
  file:
  - "${DIST_GZIP}"
  - "${DIST_ZIP}"
  - ChangeLog
  on:
    repo: ViennaRNA/pourRNA
    tags: true
